version: '3'

networks:
    laravel:

services:
    app:
        build: .
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        networks:
            - laravel

    db:
        image: mysql:5.7
        container_name: db
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
#        volumes:
#            - dbdata:/var/lib/mysql
        environment:
            MYSQL_DATABASE: crud-pessoa
            MYSQL_ROOT_PASSWORD: 123456
#            SERVICE_TAGS: dev
#            SERVICE_NAME: mysql
        networks:
            - laravel
volumes:
    dbdata:
